### ISSUE TITLE
Peer dependency does not include vite 5

### ISSUE THREAD

**Issue by DreierF** [bluwy/vite-plugin-warmup#9]
When installing the plugin together with vite 5 pnpm complains, because the peer dependency range specified by the warmup plugin does not include vite 5. It seems to work fine though.

Could you please officially update the version range to include vite 5?

```
 WARN  Issues with peer dependencies found
.
└─┬ vite-plugin-warmup 0.1.0
  └── ✕ unmet peer vite@^4.3.1: found 5.0.0
```

**Comment by bluwy** [comment]
Warmup is actually already included in Vite 5 at `server.warmup`. We should update the readme to specify that.

**Comment by DreierF** [comment]
Great! Sorry I read over that part in the announcement blogpost.
